### PR TITLE
#19

### PR DESCRIPTION
**Pull request by sagaarr**
## Description

- classes Timetable UI integration 
- code formatting 
- code splitting  

### Changes

- Timetable integration and code optimisation

### CODE REVIEW

**Review by Shruti3004 — CHANGES_REQUESTED** [review]
Hey @sagaarr can you please delete `package-lock.json`

**Comment by Shruti3004** [comment]
And @sagaarr it will be helpful if you can share the screen shot or a working demo for this PR.

**Comment by sagaarr** [comment]
https://user-images.githubusercontent.com/31507379/160382065-43b7894c-e2a5-4a58-915b-a870a9963ae0.mov

**Comment by sagaarr** [comment]
@Shruti3004 please check and verify

**Comment by sagaarr** [comment]
image

**Comment by sagaarr** [comment]
image

**Comment by sagaarr** [comment]
image

**Comment by sagaarr** [comment]
image

**Pull request merged**
