### PR TITLE
fix: #58  - Common-lib build is failing

### PR DESCRIPTION
**Pull request by arajput**
## Description

Please describe the changes in your pull request in few words here.

### Changes

List the changes done to fix a bug or introducing a new feature.

## How to test

Describe the steps required to test the changes proposed in the pull request.

Please consider using the closing keyword if the pull request is proposed to
fix an issue already created in the repository
(https://help.github.com/articles/closing-issues-using-keywords/)

### CODE REVIEW

**Review by ChakshuGautam — COMMENTED** [review]
Hey, can you please fix the typo in module name and push again. Thanks.

**Comment by ChakshuGautam** [comment]
@Shruti3004 can we remove the PR template as it may not be helpful for very small changes.

**Comment by Shruti3004** [comment]
> @Shruti3004 can we remove the PR template as it may not be helpful for very small changes.

Yes sure

**Comment by arajput** [comment]
> Hey, can you please fix the typo in module name and push again. Thanks.

Can you please point out the typo error. i  which  moodule and  file you referring

**Pull request merged**
