### PR TITLE
fix: i18n for module + github  action for build check

### PR DESCRIPTION
**Pull request by arajput**
## Description
This includes two changes
1. i18n for module.
with modules deployed on same server  translation files were not getting loaded when module is accessed as standalone.
2. github action to verify the build. It runs format:check, build  command on every  push

### Changes

i18n fixes in common-lib
i18n translation file separated and kept along with student module.

new github action file

### CODE REVIEW

**Comment by ChakshuGautam** [comment]
@arajput is there a way to reduce duplicate `student.json` file in each module? I don't mind getting this duplicated but keeping it consistent will be a challenge.

**Comment by arajput** [comment]
> @arajput is there a way to reduce duplicate `student.json` file in each module? I don't mind getting this duplicated but keeping it consistent will be a challenge.
approach 1:
we can load the translation files from common  place. So as a module developer i have  to create translation file from remote common place. but in  that case modules related translation files are kept outside module at common place.
There is also a concept of common  translation server which stores  and serves translations  to all modules.
approach 2  -
implement i18next backend plugin  to load the translation files from remote  modules url based on modules dependency. in this approach module  translation files are separated and kept along with  module. but we need to implement the library plugin to extend i18next for module federation.  

We need to  discuss on  this strategy.

**Comment by Shruti3004** [comment]
Hey @arajput can you run the script `yarn run format` in root.

**Comment by ChakshuGautam** [comment]
Also, @arajput can you add a description to what this PR is doing. Will help reviewers understand the scope of the changes.

**Comment by arajput** [comment]
> 

description updated

**Comment by arajput** [comment]
> Also, @arajput can you add a description to what this PR is doing. Will help reviewers understand the scope of the changes.

---
@Shruti3004 - i dont want to include the code formatting fixes  along with feature fixes. so i did  not include the changes related  to  yarn format hence  did not include format fixes. can we merge that in separate PR?

**Comment by arajput** [comment]
created discussion thread - https://github.com/shiksha-platform/shiksha-community/discussions/28

**Comment by Shruti3004** [comment]
Hey @arajput because of formatting the CI check is failing, can you please fix that?

**Pull request merged**
